version: 2
snapshot:
  widths:
    - 1440
  percy-css: |
    [data-hook="giphySelector"] {
      display: none; 
    }
    video[aria-label="gif"] {
      display: none;
    }

    [data-hook="addPluginFloatingToolbar"] {
      display: none;
    }
discovery:
  disable-cache: true
